Update win_test.yml

diff --git a/.github/workflows/win_test.yml b/.github/workflows/win_test.yml
--- a/.github/workflows/win_test.yml
+++ b/.github/workflows/win_test.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - main
   pull_request_target:
+    types: [opened, synchronize, labeled, unlabeled, reopened]
     branches:
       - main
   workflow_dispatch:
@@ -18,43 +19,16 @@ env:
   PYTHON_VERSION: "3.10.9"
 
 jobs:
-  approval-check:
-    runs-on: ubuntu-latest
-    steps:
-      # 判断是否需要审批
-      - name: Check if approval is required
-        id: check-approval
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const reviews = await github.rest.pulls.listReviews({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              pull_number: context.payload.pull_request.number,
-            });
-            
-            // 检查是否已获批准
-            const isApproved = reviews.data.some(review => review.state === 'APPROVED');
-            const noApprovalRequiredUsers = ['user1', 'user2']; // 不需要审批的用户名列表
-            const prUser = context.payload.pull_request.user.login;
-
-            core.setOutput('approved', isApproved);
-            core.setOutput('skipApproval', noApprovalRequiredUsers.includes(prUser));
-          result-encoding: string
-
-      # 等待 Approval，如果需要
-      - name: Wait for approval
-        if: steps.check-approval.outputs.approved != 'true' && steps.check-approval.outputs.skipApproval != 'true'
-        uses: githubocto/wait-for-commit-action@v1
-        with:
-          wait-for: approval
-        timeout-minutes: 60
-
   win-basic_tests:
-    if: steps.check-approval.outputs.approved == 'true' || steps.check-approval.outputs.skipApproval == 'true'
     runs-on: windows-latest
-    needs: approval-check
+
     steps:
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'lint_pass')
+        run: |
+          echo "The 'lint_pass' label is missing. Skipping CI/CD process."
+          exit 1
+          
       - name: Checkout code
         uses: actions/checkout@v4
         with:
@@ -93,6 +67,7 @@ jobs:
           cd ..
           cp LazyLLM-Env/poetry.lock .
           ls
+          cat test.txt || echo no
 
       - name: Set up python ${{ env.PYTHON_VERSION }}
         uses: actions/setup-python@v5
@@ -141,9 +116,10 @@ jobs:
 
 
   win-charge_tests:
-    if: steps.check-approval.outputs.approved == 'true' || steps.check-approval.outputs.skipApproval == 'true'
+    if: |
+      !contains(github.event.head_commit.message, '[skip ci]')
+      && !contains(github.event.pull_request.title, '[skip ci]')
     runs-on: windows-latest
-    needs: approval-check
 
     steps:
       - uses: actions/checkout@v4
